version: '3.8'
services:
  sentinel-rasp:
    image: caeshoru/sentinel-rasp:latest
    ports: ["3000:8081"]
    environment:
      - SENTINEL_SECRET=fef5b44f38c44aa292f357aca1180f0a60db57a318a5b579b11d3ae7253be4e4
      - SENTINEL_TOKEN=15074a9c-9ccb-49bc-b18c-8ba54c1ac412
      - SENTINEL_URL=https://calm-groups-add.loca.lt/upload-intelligence
      - INTERNAL_APP_URL=http://app:3000
      - REPO_NAME=RBS3/juice-shop
      - REPO_VERSION=${{GITHUB_SHA}}

  node-exporter:
    image: prom/node-exporter:latest
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "
        receivers:
          otlp:
            protocols:
              http:
                endpoint: 0.0.0.0:4318
          hostmetrics:
            scrapers:
              cpu:
              memory:
              network:
              disk:
        processors:
          resource:
            attributes:
              - key: sentinel.token
                value: 15074a9c-9ccb-49bc-b18c-8ba54c1ac412
                action: insert
        exporters:
          otlphttp:
            endpoint: https://calm-groups-add.loca.lt/v1/logs
            headers:
              bypass-tunnel-reminder: 'true'
        service:
          pipelines:
            logs:
              receivers: [otlp]
              processors: [resource]
              exporters: [otlphttp]
            metrics:
              receivers: [hostmetrics]
              exporters: [otlphttp]
        " > /etc/otel-config.yaml;
        /otelcol-contrib --config=/etc/otel-config.yaml
