name: Sentinel Arsenal
on: [push]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: {fetch-depth: 0}
      - name: Security Scans
        run: |
          docker run --rm -v $(pwd):/path zricethezav/gitleaks:latest detect --source="/path" --report-format json --report-path l.json || echo "[]" > l.json
          docker run --rm -v $(pwd):/src returntocorp/semgrep semgrep scan --json > s.json || echo "{"results":[]}" > s.json
          docker run --rm -v $(pwd):/root/.cache/ aquasec/trivy fs / --format json > t.json || echo "{"Results":[]}" > t.json
          echo "{"site":[]}" > z.json
      - name: Ship
        run: |
          PAYLOAD=$(jq -n --arg repo_name "RBS3/juice-shop" --arg token "15074a9c-9ccb-49bc-b18c-8ba54c1ac412" --arg version "${{ github.sha }}" --arg timestamp "$(date +%s)" --argjson s "$(cat s.json)" --argjson t "$(cat t.json)" --argjson l "$(cat l.json)" --argjson z "$(cat z.json)" '$ARGS.named')
          SIG=$(echo -n "$PAYLOAD" | openssl dgst -sha256 -hmac "fef5b44f38c44aa292f357aca1180f0a60db57a318a5b579b11d3ae7253be4e4" | sed 's/.* //')
          curl -X POST "https://calm-groups-add.loca.lt/upload-intelligence" -H "X-Sentinel-Token: 15074a9c-9ccb-49bc-b18c-8ba54c1ac412" -H "X-Sentinel-Signature: $SIG" -H "Content-Type: application/json" -H "bypass-tunnel-reminder: true" -d "$PAYLOAD"
